version: "3.3"

services:
  db:
    container_name: "discord-db"
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - "discord-db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}


volumes:
  discord-db-data: